# Generated by Django 5.1.6 on 2025-02-27 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='circuit_images/'),
        ),
    ]
